# Generated by Django 3.2 on 2025-10-04 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_resource', to='scheduler.resource'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResourceAssignment',
        ),
    ]
