# Generated by Django 5.2.7 on 2025-10-04 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_resource',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_resource', to='scheduler.resource'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResourceAssignment',
        ),
    ]
