# Generated by Django 3.2 on 2025-10-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20251004_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_resource', to='scheduler.resource'),
        ),
    ]
